pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'docker-demo:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  workingDirectory: DockerDemo
  displayName: 'docker build'
