pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'docker-demo:$(build.buildId)'

steps:
- displayName: 'Docker Build'
  script: docker build -f DockerDemo/Dockerfile -t $(dockerId).azurecr.io/$(imageName) .

- displayName: 'Docker Push'
  script: |
    docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
