pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'docker-demo:$(build.buildId)'

steps:
- script: docker build -f DockerDemo/Dockerfile -t $(imageName) .
  displayName: 'Docker Build'
- script: |
    docker login -u $(dockerId).azurecr.io -p $(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  env:
    pswd: $(dockerPassword)
  displayName: 'Docker Push'
