pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'docker-demo:latest'
  imageName2: 'docker-demo:$(build.buildId)'

steps:
- script: docker build -f DockerDemo/Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
  displayName: 'Docker Build'

- script: |
    docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  displayName: 'Docker Push'
